name    'stetic-gce_compute_master'
version '0.0.1'
source  'https://github.com/stetic/puppet-gce_compute_master'
author  'Nico Puhlmann'
license 'Apache License 2.0'
summary 'GCE Puppet Open Source master Module'
description 'GCE Module for installing Puppet master Open Source edition'
project_page 'https://github.com/stetic/puppet-gce_compute_master'
dependency 'puppetlabs/gce_compute', '>= 0.4.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 1.0.0'